SELECT USER_NAME
    ,ERROR_MESSAGE
    ,COUNT(*) NUM_OF_FAILURES 
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY 
WHERE IS_SUCCESS = 'NO' 
GROUP BY USER_NAME
    ,ERROR_MESSAGE 
ORDER BY NUM_OF_FAILURES DESC;