SELECT NAME
    ,DATEDIFF('DAY', PASSWORD_LAST_SET_TIME, CURRENT_TIMESTAMP()) || ' days ago' AS PASSWORD_LAST_CHANGED  
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS  
WHERE DELETED_ON IS NULL 
    AND PASSWORD_LAST_SET_TIME IS NOT NULL 
ORDER BY PASSWORD_LAST_SET_TIME;  