SELECT USER_NAME AS BY_WHOM
    ,DATEDIFF('day', START_TIME, CURRENT_TIMESTAMP()) || ' days ago' AS CREATED_ON
    ,ADD_MONTHS(START_TIME, 6) AS EXPIRES_ON
    ,DATEDIFF('day', CURRENT_TIMESTAMP(), ADD_MONTHS(END_TIME, 6)) AS EXPIRES_IN_DAYS 
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY 
WHERE EXECUTION_STATUS = 'SUCCESS' 
    AND QUERY_TEXT ILIKE 'SELECT%SYSTEM$GENERATE_SCIM_ACCESS_TOKEN%' 
    AND QUERY_TEXT NOT ILIKE 'SELECT%WHERE%SYSTEM$GENERATE_SCIM_ACCESS_TOKEN%' 
ORDER BY EXPIRES_IN_DAYS;  