SELECT NAME
    ,DATEDIFF("day", NVL(LAST_SUCCESS_LOGIN, CREATED_ON), CURRENT_TIMESTAMP()) || ' days ago' AS LAST_LOGIN 
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS  
WHERE DELETED_ON IS NULL 
ORDER BY DATEDIFF("day", NVL(LAST_SUCCESS_LOGIN, CREATED_ON)
    ,CURRENT_TIMESTAMP()) DESC; 