ALTER SESSION SET TIMEZONE = UTC; 

SELECT 
    DATE(START_TIME), 
    EXECUTION_STATUS, 
    USER_NAME, 
    WAREHOUSE_NAME, 
    TOTAL_ELAPSED_TIME, 
    ERROR_CODE, 
    ERROR_MESSAGE 
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.QUERY_HISTORY())  
WHERE  
    (EXECUTION_STATUS = 'FAILED_WITH_ERROR' OR EXECUTION_STATUS = 'FAILED_WITH_INCIDENT') AND MONTH(START_TIME) =                      MONTH(CURRENT_DATE) AND MONTH(END_TIME) = MONTH(CURRENT_DATE) 
UNION 
SELECT 
    DATE(START_TIME), 
    EXECUTION_STATUS, 
    USER_NAME, 
    WAREHOUSE_NAME, 
    TOTAL_ELAPSED_TIME, 
    ERROR_CODE, 
    ERROR_MESSAGE 
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY  
WHERE  
    ((EXECUTION_STATUS = 'FAIL') AND IS_CLIENT_GENERATED_STATEMENT = 'FALSE') AND MONTH(START_TIME) = MONTH(CURRENT_DATE) 
    AND MONTH(END_TIME) = MONTH(CURRENT_DATE);