ALTER SESSION SET TIMEZONE = UTC; 

SELECT 
    DATE(START_TIME), 
    EXECUTION_STATUS, 
    USER_NAME, 
    WAREHOUSE_NAME, 
    TOTAL_ELAPSED_TIME
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.QUERY_HISTORY())  
WHERE  
    EXECUTION_STATUS = 'SUCCESS' 
    AND MONTH(START_TIME) = MONTH(CURRENT_DATE) 
    AND MONTH(END_TIME) = MONTH(CURRENT_DATE) 
UNION 
SELECT 
    DATE(START_TIME), 
    EXECUTION_STATUS, 
    USER_NAME, 
    WAREHOUSE_NAME, 
    TOTAL_ELAPSED_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY  
WHERE  
    ((EXECUTION_STATUS = 'SUCCESS') AND IS_CLIENT_GENERATED_STATEMENT = 'FALSE') AND MONTH(START_TIME) = MONTH(CURRENT_DATE) 
    AND MONTH(END_TIME) = MONTH(CURRENT_DATE);

SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.QUERY_HISTORY()) LIMIT 10;