ALTER SESSION SET TIMEZONE = UTC; 

SELECT NAME
    ,COUNT(*) AS RUN_COUNT 
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY 
WHERE COMPLETED_TIME >= DATE_TRUNC('MONTH', CURRENT_DATE) - INTERVAL '1 MONTH' 
    AND COMPLETED_TIME < DATE_TRUNC('MONTH', CURRENT_DATE) 
GROUP BY NAME 
ORDER BY RUN_COUNT DESC 
LIMIT 10; 