SELECT table_id
    ,ANY_VALUE(TABLE_NAME) AS TABLE_NAME
    ,SUM(PARTITIONS_SCANNED) AS TOTAL_PARTITIONS_SCANNED
    ,SUM(PARTITIONS_PRUNED) / GREATEST(SUM(PARTITIONS_SCANNED) + SUM (PARTITIONS_PRUNED) ,1) AS PRUNING_PERCENTAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_PRUNING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
GROUP BY TABLE_ID
ORDER BY TOTAL_PARTITIONS_SCANNED DESC;