ALTER SESSION SET TIMEZONE = UTC; 

SELECT  
    USER_NAME,  
    COUNT(*) TOTAL_QUERIES,  
    SUM(TOTAL_ELAPSED_TIME/1000 *  
    CASE UPPER(WAREHOUSE_SIZE) 
        WHEN 'X-SMALL' THEN 1/60/60 
        WHEN 'SMALL'   THEN 2/60/60 
        WHEN 'MEDIUM'  THEN 4/60/60 
        WHEN 'LARGE'   THEN 8/60/60 
        WHEN 'X-LARGE' THEN 16/60/60 
        WHEN '2X-LARGE' THEN 32/60/60 
        WHEN '3X-LARGE' THEN 64/60/60 
        WHEN '4X-LARGE' THEN 128/60/60 
    ELSE 0 
    END) AS ESTIMATED_CREDITS, 
    DATE(START_TIME) AS Usagedate 
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY 
WHERE  
    WAREHOUSE_NAME IS NOT NULL AND WAREHOUSE_SIZE IS NOT NULL 
    AND START_TIME >= DATEADD(DAY, -6, CURRENT_DATE()) 
GROUP BY  
    USER_NAME, DATE(START_TIME) 
ORDER BY Usagedate desc; 