SELECT 
    DATE_TRUNC('MONTH', USAGE_DATE) AS USAGE_MONTH, 
    SUM(CREDITS_BILLED) 
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY 
GROUP BY 
    USAGE_MONTH 
ORDER BY  
    SUM(CREDITS_BILLED) DESC 
LIMIT 12; 