SELECT 
    WAREHOUSE_NAME, 
    SUM(CREDITS_USED) AS TOTAL_CREDITS_USED 
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY 
GROUP BY 
    WAREHOUSE_NAME
ORDER BY 
    TOTAL_CREDITS_USED DESC 
LIMIT 10; 