ALTER SESSION SET TIMEZONE = UTC; 

SELECT  
    TO_CHAR(LAST_DAY(USAGE_DATE),'DD/MM/YYYY') AS UsageMonth, 
    SUM(DECODE(SERVICE_TYPE,'WAREHOUSE_METERING', CREDITS_BILLED)) AS WAREHOUSE_CREDITS, 
    SUM(DECODE(SERVICE_TYPE,'PIPE', CREDITS_BILLED)) AS PIPE_CREDITS, 
    SUM(DECODE(SERVICE_TYPE,'MATERIALIZED_VIEW', CREDITS_BILLED)) AS MVIEW_CREDITS, 
    SUM(DECODE(SERVICE_TYPE,'AUTO_CLUSTERING', CREDITS_BILLED)) AS CLUSTERING_CREDITS, 
    SUM(DECODE(SERVICE_TYPE,'WAREHOUSE_METERING_READER', CREDITS_BILLED)) AS READER_CREDITS, 
    SUM(CREDITS_BILLED) AS TOTAL 
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY 
WHERE  
    USAGE_DATE >= DATEADD(MONTH, -12, CURRENT_DATE()) 
GROUP BY  
TO_CHAR(LAST_DAY(USAGE_DATE),'DD/MM/YYYY'); 