ALTER SESSION SET TIMEZONE = UTC; 

WITH EXPENSIVE_QUERY AS ( 
SELECT  
    QUERY_ID, 
    USER_NAME, 
    TOTAL_ELAPSED_TIME, 
    TOTAL_ELAPSED_TIME / 1000 *  
    CASE UPPER(WAREHOUSE_SIZE) 
        WHEN 'X-SMALL' THEN 1/60/60 
        WHEN 'SMALL'   THEN 2/60/60 
        WHEN 'MEDIUM'  THEN 4/60/60 
        WHEN 'LARGE'   THEN 8/60/60 
        WHEN 'X-LARGE' THEN 16/60/60 
        WHEN '2X-LARGE' THEN 32/60/60 
        WHEN '3X-LARGE' THEN 64/60/60 
        WHEN '4X-LARGE' THEN 128/60/60 
   ELSE 0 
   END AS ESTIMATED_CREDITS 
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.QUERY_HISTORY()) 
WHERE 
    DATE(START_TIME) >= DATEADD('DAY',-30,CURRENT_DATE) 
UNION 
SELECT  
    QUERY_ID, 
    USER_NAME, 
    TOTAL_ELAPSED_TIME, 
    TOTAL_ELAPSED_TIME / 1000 *  
    CASE UPPER(WAREHOUSE_SIZE) 
        WHEN 'X-SMALL' THEN 1/60/60 
        WHEN 'SMALL'   THEN 2/60/60 
        WHEN 'MEDIUM'  THEN 4/60/60 
        WHEN 'LARGE'   THEN 8/60/60 
        WHEN 'X-LARGE' THEN 16/60/60 
        WHEN '2X-LARGE' THEN 32/60/60 
        WHEN '3X-LARGE' THEN 64/60/60 
        WHEN '4X-LARGE' THEN 128/60/60 
   ELSE 0 
   END AS ESTIMATED_CREDITS 
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY 
WHERE 
    DATE(START_TIME) >= DATEADD('DAY',-30,CURRENT_DATE) 
) 
SELECT * FROM EXPENSIVE_QUERY ORDER BY ESTIMATED_CREDITS DESC LIMIT 1; 