ALTER SESSION SET TIMEZONE = UTC; 

SELECT WAREHOUSE_NAME
    ,COUNT(*) AS TOTAL_QUERIES 
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.QUERY_HISTORY()) 
WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP) 
    AND WAREHOUSE_NAME IS NOT NULL 
GROUP BY WAREHOUSE_NAME 
ORDER BY TOTAL_QUERIES DESC; 