SELECT WAREHOUSE_NAME
    ,COUNT(*) AS TOTAL_QUERIES 
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY 
WHERE EXECUTION_STATUS = 'FAIL' 
    AND WAREHOUSE_NAME IS NOT NULL 
GROUP BY WAREHOUSE_NAME 
ORDER BY TOTAL_QUERIES DESC 
LIMIT 10; 