ALTER SESSION SET TIMEZONE = UTC; 

SELECT DATABASE_NAME
    ,SUM(AVERAGE_DATABASE_BYTES)/POWER(1024,2) AS TOTAL_AVERAGE_DATABASE_BYTES
    ,SUM(AVERAGE_FAILSAFE_BYTES)/POWER(1024,2) AS TOTAL_AVERAGE_FAILSAFE_BYTES 
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.DATABASE_STORAGE_USAGE_HISTORY(DATEADD('DAYS', -30, CURRENT_DATE()))) 
WHERE DATABASE_NAME NOT LIKE 'DROPPED%'
GROUP BY DATABASE_NAME; 