SELECT TABLE_NAME
    ,ACTIVE_BYTES/1024 AS ACTIVE_BYTES_KB
    ,FAILSAFE_BYTES/1024 AS FAILSAFE_BYTES_KB
    ,TIME_TRAVEL_BYTES/1024 AS TIME_TRAVEL_BYTES_KB
    ,(ACTIVE_BYTES_KB + FAILSAFE_BYTES_KB + TIME_TRAVEL_BYTES_KB) AS TOTAL_STORAGE_KB
FROM SNOWFLAKE.INFORMATION_SCHEMA.TABLE_STORAGE_METRICS 
WHERE TABLE_NAME!='MONITOR_TABLE' 
    AND TABLE_DROPPED IS NULL
ORDER BY TOTAL_STORAGE_KB DESC
LIMIT 10;  