ALTER SESSION SET TIMEZONE = UTC; 

SHOW USERS; 

SELECT "name"
    ,CASE  
        WHEN "last_success_login" <= DATEADD(DAY, -10, CURRENT_DATE) THEN 'INACTIVE'  
    ELSE  
        'ACTIVE'  
    END STATUS 
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))  
ORDER BY STATUS;