WITH LOGIN_USERS_CTE AS (
    SELECT USER_NAME
        ,CLIENT_IP 
    FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY 
    UNION 
    SELECT USER_NAME
        ,CLIENT_IP 
    FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.LOGIN_HISTORY())) 
SELECT DISTINCT USER_NAME
    ,COUNT(CLIENT_IP) AS NO_OF_DIFF_IPS 
FROM LOGIN_USERS_CTE 
GROUP BY USER_NAME 
HAVING COUNT(CLIENT_IP) > 1;